"""add unique constraint

Revision ID: baa04efd3b91
Revises: d4fe955f7a7b
Create Date: 2023-09-01 16:43:09.530252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa04efd3b91'
down_revision: Union[str, None] = 'd4fe955f7a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.create_unique_constraint(None, 'directors', ['number_of_films'])
    op.create_unique_constraint(None, 'directors', ['nationality'])
    op.create_unique_constraint(None, 'directors', ['birthday'])
    op.create_unique_constraint(None, 'directors', ['name'])
    op.create_unique_constraint(None, 'movies', ['title'])
    op.create_unique_constraint(None, 'movies', ['director_id'])
    op.create_unique_constraint(None, 'movies', ['movie_length'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_constraint(None, 'directors', type_='unique')
    op.drop_constraint(None, 'directors', type_='unique')
    op.drop_constraint(None, 'directors', type_='unique')
    op.drop_constraint(None, 'directors', type_='unique')
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.Column('comment', sa.VARCHAR(), nullable=True),
    sa.Column('movie_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
